### ISSUE TITLE
Add a Parquet Convertor 

### ISSUE THREAD

**Issue by rxm7706** [sanders41/sas7bdat-converter#265]
Currently supported conversions are csv, Excel (xlsx format), json, Pandas DataFrame, and XML.

It would be very useful to add a to_parquet function
sas7bdat_converter.to_parquet('/path/to/sas7bdat/file/example.sas7bdat', 'path/to/new/file/example.parquet')

References
https://stackoverflow.com/questions/41066582/python-save-pandas-data-frame-to-parquet-file
https://documentation.sas.com/doc/en/pgmsascdc/v_031/enghdff/p1ht5enj2pwsiyn1tnxtvao89b6d.htm
https://documentation.sas.com/doc/en/pgmsascdc/v_031/enghdff/n09xjo6gq5lqxln1xcdooxy33egd.htm

**Comment by sanders41** [comment]
Thanks @rxm7706 this seems like good addition. I'm happy to accept a PR for this if you want to add it.

**Comment by rxm7706** [comment]
@elanqo @cshaley could you take a look please.
