### ISSUE TITLE
Publish a Conda Packaged Version

### ISSUE THREAD

**Issue by rxm7706** [sanders41/sas7bdat-converter#266]
This is definitely one of the cleanest and best converters for actively maintained sas7bdat converters available today. 
Would it be possible to add a conda packaged version of this module on conda-forge
It would help the conda only ecosystems and promote usage and contributions from a larger community. 

https://www.marcelotrevisani.com/grayskull
generates what looks like a great first pass of a conda meta.yaml

### Sample Recipe

{% set name = "sas7bdat-converter" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sas7bdat_converter-{{ version }}.tar.gz
  sha256: 1d8a672eb7d1bc218ce874c147442d4de239934eff2945e6d2b3feff01387169

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - pandas >=1.2.0,<2.0.0
    - python >=3.6,<4.0

test:
  imports:
    - sas7bdat_converter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sanders41/sas7bdat-converter
  summary: Convert sas7bdat and xport files into other formats
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sanders41

**Comment by sanders41** [comment]
I've never used conda myself, but this seems like a reasonable suggestion. I'll look into adding it.

**Comment by rxm7706** [comment]
https://anaconda.org/conda-forge/sas7bdat-converter

conda install -c conda-forge sas7bdat-converter 

If it works as expected, maybe we can update the readme / installation options.

**Comment by sanders41** [comment]
Sure, I would accept a PR adding it to the README.

**Comment by rxm7706** [comment]
https://github.com/sanders41/sas7bdat-converter/pull/294

**Comment by sanders41** [comment]
Closed via #294
